//
//  ICPField.h
//  IBMCaptureSDK
//
//  Copyright (c) 2016 IBM Corporation. All rights reserved.
//

#import "ICPObject.h"

#import "ICPRect.h"

NS_ASSUME_NONNULL_BEGIN

@protocol ICPCharacter;
/**

 The ICPField protocol represents a piece of information with a type and a value. It can be attached to batches, documents,
 pages, or other fields.

 @see ICPBatch
 @see ICPDocument
 @see ICPPage
 */
@protocol ICPField <ICPObject>

/** The value of the field. */
@property (nonatomic, strong, nullable) id value;

/** The ICPCharacters recognised by OCR */
@property (nonatomic, strong) NSArray<id<ICPCharacter> > *characters;

/** The position to be used for OCR */
@property (nonatomic, assign) ICPRect position;

/**
 Notify field that it has been changed manually so information generated by OCR must be removed as it is no longer valid
 */
- (void)reset;

/**
 Adds a character to the field.
 @param character The character to add to the field.
 */
- (void)addCharacter:(id<ICPCharacter>)character;

/**
 Removes a character from the field.
 @param character The character to remove from the field.
 */
- (void)removeCharacter:(id<ICPCharacter>)character;

/**
 Reorders characters in the field.
 @param atIndex The index from where the character should be moved.
 @param toIndex The index to where the character should be moved.
 */
- (void)moveCharacterAtIndex:(NSUInteger)atIndex toIndex:(NSUInteger)toIndex;

/**
 Inserts a character at the given index.
 @param character The character to be inserted.
 @param index The index where the character should be inserted.
 */
- (void)insertCharacter:(id<ICPCharacter>)page atIndex:(NSUInteger)index;



@end

NS_ASSUME_NONNULL_END
